### ISSUE TITLE
map vote prompts twice

### ISSUE THREAD

**Issue by flueysucks** [koopa516/ParkourFortress-Bugs#26] opened 2019-05-14 00:49 UTC
Server cvar 'sm_nextmap' changed to pf_overview_b3
Vote Completed! The next map will be: pf_overview_b3
Warning | Max velocity exceeded.
Server cvar 'sm_nextmap' changed to pf_koosu_s8
Vote Completed! The next map will be: pf_koosu_s8

**Comment by Kenzzer** [comment] 2019-05-14 07:20
Not a bug, just sourcemod displaying a cvar value that has been changed. This can be resolved by changing our method for updating the cvar.

**Comment by koopa516** [comment] 2019-05-20 04:44
Fixed in commit 347f3b

**Closed by koopa516** 2019-05-20 04:44 UTC
Labels: enhancement, not a bug
